name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Creating an image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/nodeimage
      -
        name: Running Image on Particular port
        run: docker run -p 3000:3000 -d ${{ secrets.DOCKERHUB_USERNAME }}/nodeimage
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodeimage
