name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}:$(date +%s)
    - name: Running a Docker Image
      run: docker run -p 3000:3000 -d ${{ secrets.DOCKERHUB_USERNAME }}:$(date +%s)
    - name: Login to DockerHub
      run: docker login
      env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pushing Docker Image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}:$(date +%s)
